language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qtbase5-dev
            - qttools5-dev
            - liblua5.2-dev
            - libcairo2-dev
            - libpango1.0-dev
            - libboost-all-dev
            - libqt5svg5-dev
            - libgtest-dev
            - libeigen3-dev
            - libcurl4-gnutls-dev
            - libgtk-3-dev
            - libgdk-pixbuf2.0-dev
            - gcc-4.9
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

      script:
        - ./scripts/travis.sh

    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-testz
            - llvm-toolchain-trusty-6.0
          packages:
            - qtbase5-dev
            - qttools5-dev
            - liblua5.2-dev
            - libcairo2-dev
            - libpango1.0-dev
            - libboost-all-dev
            - libqt5svg5-dev
            - libgtest-dev
            - libeigen3-dev
            - libcurl4-gnutls-dev
            - libgtk-3-dev
            - libgdk-pixbuf2.0-de
            - clang-6.0
            - clang-tidy-6.0

      script:
        - ./scripts/clang-tidy.sh

cache: ccache

before_install:
  - eval "${MATRIX_EVAL}"
