language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      compiler: gcc
      addons:
        apt:
          packages:
            - qtbase5-dev
            - qttools5-dev
            - liblua5.2-dev
            - libcairo2-dev
            - libpango1.0-dev
            - libboost-all-dev
            - libqt5svg5-dev
            - libgtest-dev
            - libeigen3-dev
            - libcurl4-gnutls-dev
            - libgtk-3-dev
            - libgdk-pixbuf2.0-dev   

      services:
      - xvfb

      script:
      - ./scripts/travis.sh

cache: ccache

before_script:
  - "export DISPLAY=:99.0"
