language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qtbase5-dev
            - qttools5-dev
            - liblua5.2-dev
            - libcairo2-dev
            - libpango1.0-dev
            - libboost-all-dev
            - libqt5svg5-dev
            - libgtest-dev
            - libeigen3-dev
            - libcurl4-gnutls-dev
            - libgtk-3-dev
            - libgdk-pixbuf2.0-dev
            - mesa-common-dev
            - libglew1.5-dev 
            - libglm-dev
            - libglew-dev
            - gcc-4.9
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

      script:
        - ./scripts/travis.sh

cache: ccache

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - eval "${MATRIX_EVAL}"
